Pre release (code review needed)
AudioKit/MIDITrackView pull request #1
Opened 2023-12-15 17:48 UTC by emurray2

This commit fixes AudioKit/AudioKitUI#46 and AudioKit/AudioKitUI#47. Rewrote the MIDITrackView entirely in SwiftUI, used `drawingGroup()` to render one path layer for the notes to improve drawing efficiency and created MIDITrackViewModel to store note rectangles and track properties for drawing.

2024-01-13 01:47 UTC, emurray2 commented
Hi @aure @wtholliday @orchetect . Was wondering if any of you wanted to check this out. No rush, but I want to publish this soon somewhere so I can share it with the community.

2024-01-23 22:08 UTC, wtholliday requested changes

2024-01-23 22:08 UTC, wtholliday commented on Sources/MIDITrackView/MIDITrackView.swift
> +struct MIDINoteView: Shape {
Probably should be called `MIDINotesView` (plural)

2024-01-23 22:08 UTC, wtholliday commented on Sources/MIDITrackView/MIDITrackView.swift
> +    let midiNotes: [CGRect]
Call this `noteRects`

2024-01-23 22:08 UTC, wtholliday commented on MIDITrackView.playground/Contents.swift
> +            CGRect(x: 0.5, y: 0.0, width: 1.0, height: 10.0),
Again, it's odd for something called `midiNotes` to be `CGRects`

2024-02-03 22:37 UTC, aure approved these changes

2024-02-03 22:39 UTC, merged